### ISSUE TITLE
Empty dir has internal height of 0px making it impossible to right click for context menu

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-navigator#113]
![1](https://github.com/KKoukiou/cockpit-navigator/assets/14921356/c25ed476-14b9-40ba-94ba-82bc6c2722a0)

**Comment by ashutosh7i** [comment]
Hello @KKoukiou mam, i am working on this issue, 
can you please assign it to me?

also upon looking at the code, i think it isn't a normal issue that can be solved by tweaking css , it is more complex issue which will require me to play with conditional operators, do you have any suggestions or any advice for me regarding this issue?

**Comment by garrett** [comment]
(I need to work on other issues, but wanted to take a peek at this and wanted to give you a few hints. Ping me in Matrix if you're having a hard time with this issue.)

**Comment by garrett** [comment]
Sure, that works for me. Thanks!

A few minor suggestions:

- Change the text to "Directory is empty" (only the first letter is capitalized). Cockpit uses "Sentence case", where just the first letter is capitalized, with an exception for proper nouns. (PF has more info @ https://www.patternfly.org/ux-writing/capitalization)
- Don't hardcode the size to pixels. It should, instead, use padding based on PatternFly sizes. It's an empty state, so it should be `var(--pf-v5-global--spacer--xl)`, as seen in the demos @ https://www.patternfly.org/components/table/react-demos#empty-states and https://www.patternfly.org/components/empty-state/design-guidelines — We can use an empty state instead... however, we don't need icons, sub text, action text, and so on. 
 
> The context menu can be envoked from anywhere in the area.

Anywhere in the content area (where the files and directories go), not on the page, right?

**Comment by ashutosh7i** [comment]
i am glad my pr is acceptable,

few questions-
1. The current message is "Directory is empty." you want me to change it to "Directory is empty" (no ".") ??
2. so instead of hard coded variable we should use patternfly,
I am new to this patternfly but seems pretty east to work with.
i have visited link https://www.patternfly.org/components/empty-state/design-guidelines
and Indeed using empty state is a good idea, 

I implemented following empty state component-
```
<EmptyState>
<EmptyStateHeader titleText="Directory is empty" headingLevel="h4" />
 </EmptyState>
```
this component handles the space automatically, also the functionality is as it was.

3. Yes anywhere in context menu where the files and directories go and not on the page, 

video -
![output](https://github.com/cockpit-project/cockpit-navigator/assets/44861896/dd623e38-922d-473f-a8a2-775243a01b1d)

Everything is good?
@garrett

**Comment by garrett** [comment]
> The current message is "Directory is empty." you want me to change it to "Directory is empty" (no ".") ??

Correct. No period for UI text, as they're phrases. The exception is if there are multiple sentences to explain something (but then it's not really UI text).

**Comment by garrett** [comment]
I cannot approve anything in the issue here; there is no PR. It's definitely more than good enough for a PR. Thanks for your work on this! Looking forward to it. :grin:

**Comment by ashutosh7i** [comment]
Wow, i am amazed 🤩 by the resources you have given,
i never explored Design this much, but now i find it interesting, i will read whole docs and will try my next project to be using these specifications,
ps: Thank you @garrett sire 🤗 so much to learn with OSC.

Coming back to the issue-
> The first is the heading, the second is the "No results found" text by itself, and the third is the sub-text explaining. I would've jumped down to around that size, weight and shade of grey, but PF has different ideas, I guess.

here the "No results found" is called EmptyStateBody in PF
and code for that will be-
```

![image](https://github.com/cockpit-project/cockpit-navigator/assets/44861896/19f6689a-9665-4cbe-bacb-e23176439e24)
