### ISSUE TITLE
Can't reach the root directory

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-navigator#127]
[Screencast from 2023-09-27 10-47-47.webm](https://github.com/cockpit-project/cockpit-navigator/assets/108616679/15e0da38-3b51-481f-9127-16e398cfaee8)

**Comment by KKoukiou** [comment]
thanks @subhoghoshX for taking a look.

This issue was detected some time ago and an attempt to fix that exists on https://github.com/cockpit-project/cockpit-navigator/pull/92 . I did not have time to finish that PR unfortunately.
