### ISSUE TITLE
Create link dialog has redundant / on the file prefix paths

### ISSUE THREAD

**Issue by KKoukiou** [cockpit-project/cockpit-navigator#136]
![Screen Shot 2023-10-04 at 11 28 06](https://github.com/cockpit-project/cockpit-navigator/assets/14921356/44b4a594-aeb2-493e-aaf9-97db6d9c3771)

**Comment by subhoghoshX** [comment]
I think it persists on main branch as well.

![image](https://github.com/cockpit-project/cockpit-navigator/assets/108616679/44920e30-999e-48d3-a9b6-ca97e0c64afa)

It just copies the extra `/`s from input to the menu.
