### ISSUE TITLE
"Edit properties" menu item vs. "permissions" modal title

### ISSUE THREAD

**Issue by allisonkarlitskaya** [cockpit-project/cockpit-navigator#207]
Probably we should either change the dialog to be "properties" or the menu item to be "permissions"?  I'm happy to do a patch either way.  @garrett thoughts?

**Comment by garrett** [comment]
Yeah, the properties dialog just contains permissions now, so that makes sense to have it be consistent in both places as "permissions". :+1: Thanks for pointing this out!
