### ISSUE TITLE
Include lockfile in repo

### ISSUE THREAD

**Issue by redxtech** [cockpit-project/cockpit-navigator#216]
Is there a reason you don't check in the `package-lock.json` or whichever other lockfile you are using?

I'm trying to build this package for NixOS, but all the steps are failing because there's no lockfile to use for precise package versions.

Including it would be great for making builds more reliable everywhere!

**Comment by martinpitt** [comment]
We generally don't track package-lock.json in git. The *release tarballs* do contain it though, so any other cockpit-* project has them. But navigator doesn't have a release yet as we are still [have a bunch of blockers](https://github.com/cockpit-project/cockpit-navigator/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22First+official+release%22) before we consider it good enough for releasing.
