### ISSUE TITLE
Cannot delete directory or file with spaces

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-navigator#238]
![image](https://github.com/cockpit-project/cockpit-navigator/assets/67428/fe47a5b2-5939-44d9-ab28-bbda699694d9)

**Comment by allisonkarlitskaya** [comment]
Doesn't look like the space are the problem so much as the `admin` at the front?

**Comment by MahmoudHamdy02** [comment]
Hmm, can't reproduce this. I've also tried leading & trailing whitespace, and files & folders created inside cockpit and from the terminal

**Comment by jelly** [comment]
Woops, sounds like something I encountered when refactoring. Closing.
