### ISSUE TITLE
Clicking on a symlink of the current directory is super confusing

### ISSUE THREAD

**Issue by jelly** [cockpit-project/cockpit-navigator#262]
`lolol` is a symlink of `/home/admin` so if you click it you keep going deeper into `/home/admin/lolol`
![image](https://github.com/cockpit-project/cockpit-navigator/assets/67428/1805dbf8-583d-43f7-a32e-00649f059555)

**Comment by allisonkarlitskaya** [comment]
Is this a bug?

**Comment by jelly** [comment]
@allisonkarlitskaya no :)
